-- vim.cmd([[source ~/.config/nvim/backup_init.vim]])
require("user/options")
require("user/keymaps")
require("user/bclose")
require("user/run_file")
require("lsp")
require("user.lazy")
require("user.custom-colors")
